/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _protectedRouteImport } from './routes/__protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _protectedUserPanelRouteImport } from './routes/__protected/user-panel'
import { Route as _protectedDashboardRouteImport } from './routes/__protected/dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedRoute = _protectedRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedUserPanelRoute = _protectedUserPanelRouteImport.update({
  id: '/user-panel',
  path: '/user-panel',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedDashboardRoute = _protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _protectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof _protectedDashboardRoute
  '/user-panel': typeof _protectedUserPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof _protectedDashboardRoute
  '/user-panel': typeof _protectedUserPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__protected': typeof _protectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/__protected/dashboard': typeof _protectedDashboardRoute
  '/__protected/user-panel': typeof _protectedUserPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/dashboard' | '/user-panel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/dashboard' | '/user-panel'
  id:
    | '__root__'
    | '/'
    | '/__protected'
    | '/login'
    | '/register'
    | '/__protected/dashboard'
    | '/__protected/user-panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _protectedRoute: typeof _protectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _protectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected/user-panel': {
      id: '/__protected/user-panel'
      path: '/user-panel'
      fullPath: '/user-panel'
      preLoaderRoute: typeof _protectedUserPanelRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/dashboard': {
      id: '/__protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _protectedDashboardRouteImport
      parentRoute: typeof _protectedRoute
    }
  }
}

interface _protectedRouteChildren {
  _protectedDashboardRoute: typeof _protectedDashboardRoute
  _protectedUserPanelRoute: typeof _protectedUserPanelRoute
}

const _protectedRouteChildren: _protectedRouteChildren = {
  _protectedDashboardRoute: _protectedDashboardRoute,
  _protectedUserPanelRoute: _protectedUserPanelRoute,
}

const _protectedRouteWithChildren = _protectedRoute._addFileChildren(
  _protectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _protectedRoute: _protectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
